name: Bug report
description: File a bug report.
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: |
        Tell us what you experienced!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install using method...
        2. Run this command...
        3. See error...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: Please copy and paste the exact output of running vc_version.
  - type: dropdown
    id: install-method
    attributes:
      label: How did you install the software?
      options:
        - Homebrew
        - Docker
        - Built from source
  - type: checkboxes
    id: operating-systems
    attributes:
      label: On which operating systems have you experienced this issue?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant program output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/educelab/open-source-consortium/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true