#pragma once

/** @file */

#include <educelab/core/types/Signals.hpp>

#include "vc/core/neighborhood/LineGenerator.hpp"
#include "vc/texturing/TexturingAlgorithm.hpp"

namespace volcart::texturing
{
/**
 * @class LayerTexture
 * @author Seth Parker
 * @date 11/24/2016
 *
 * @brief Generate a Texture of layered images
 *
 * The Texture generated by this class contains multiple texture images. Each
 * image is the projection of the mesh some distance through the Volume along
 * each point's surface normal. For well-formed meshes and parameterizations,
 * this amounts to resampling the Volume into a flattened subvolume with the
 * segmentation mesh forming a straight line at its center.
 *
 * @ingroup Texture
 */
class LayerTexture : public TexturingAlgorithm
{
public:
    /** Pointer type */
    using Pointer = std::shared_ptr<LayerTexture>;

    /** Signal type */
    using ImageCompleteSignal = Signal<std::size_t, std::size_t, cv::Mat>;

    /** Make shared pointer */
    static auto New() -> Pointer;

    /** Default constructor */
    LayerTexture() = default;
    /** Default destructor */
    ~LayerTexture() override = default;
    /** Default copy constructor */
    LayerTexture(LayerTexture&) = default;
    /** Default move constructor */
    LayerTexture(LayerTexture&&) = default;
    /** Default copy operator */
    auto operator=(const LayerTexture&) -> LayerTexture& = default;
    /** Default move operator */
    auto operator=(LayerTexture&&) -> LayerTexture& = default;

    /**
     * @brief Set the Neighborhood generator
     *
     * This class only supports LineGenerator
     */
    void setGenerator(LineGenerator::Pointer g);

    /**
     * @brief Enable or disable eager rendering mode
     *
     * When enabled, the algorithm generates one complete layer image at a time
     * (iterating over pixels for each layer offset), rather than the default
     * mode which iterates over pixels and computes all layer offsets per pixel.
     * Eager mode emits the imageComplete signal after each layer is finished,
     * allowing incremental output (e.g., writing layers to disk as they are
     * produced).
     */
    void setEagerMode(bool enable);

    /** @brief Returns whether eager rendering mode is enabled */
    [[nodiscard]] auto getEagerMode() const -> bool;

    void setEagerCache(bool enable);

    [[nodiscard]] auto getEagerCache() const -> bool;

    /**
     * @brief Signal emitted after each layer image is completed in eager mode
     *
     * The signal is emitted with the layer index, the total number of layers,
     * and the completed layer image (as a cv::Mat).
     *
     * @see setEagerMode()
     */
    ImageCompleteSignal imageComplete;

    /**@{*/
    /** @brief Compute the Texture */
    auto compute() -> Texture override;
    /**@}*/
private:
    /** Neighborhood Generator */
    LineGenerator::Pointer gen_;

    /** Eager mode */
    bool eager_{false};
    /** Whether to cache images when eager mode is enabled */
    bool eagerCache_{false};
};

}  // namespace volcart::texturing
