#pragma once

#include "vc/core/types/PerPixelMap.hpp"
#include "vc/core/types/Texture.hpp"
#include "vc/core/types/Volume.hpp"

namespace volcart
{
namespace texturing
{
/**
 * @class LayerTexture
 * @author Seth Parker
 * @date 11/24/2016
 *
 * @brief Generate a Texture of layered images
 *
 * The Texture generated by this class contains multiple texture images. Each
 * image is the projection of the mesh some distance through the Volume along
 * each point's surface normal. For well-formed meshes and parameterizations,
 * this amounts to resampling the Volume into a flattened subvolume with the
 * segmentation mesh forming a straight line at its center.
 *
 * @ingroup Texture
 */
class LayerTexture
{
public:
    /**@{*/
    /** @brief Set the input PerPixelMap */
    void setPerPixelMap(PerPixelMap ppm) { ppm_ = std::move(ppm); }

    /** @brief Set the input Volume */
    void setVolume(Volume::Pointer vol) { vol_ = std::move(vol); }

    /** @brief Set the sampling search radius: the distance from the mesh to
     * consider for compositing */
    void setSamplingRadius(double r) { radius_ = r; }

    /**
     * @brief Set the sampling interval: how frequently the voxels along the
     * radius are sampled for compositing purposes
     *
     * Default = 1.0
     */
    void setSamplingInterval(double i) { interval_ = i; }

    /**
     * @brief Set the filtering search direction: which "side" of the mesh to
     * consider when compositing
     *
     * Default: Bidirectional
     */
    void setSamplingDirection(Direction d) { direction_ = d; }
    /**@}*/

    /**@{*/
    /** @brief Compute the Texture */
    Texture compute();
    /**@}*/

    /**@{*/
    /** @brief Get the generated Texture */
    const Texture& getTexture() const { return result_; }

    /** @copydoc getTexture() const */
    Texture& getTexture() { return result_; }
    /**@}*/

private:
    /** PPM */
    PerPixelMap ppm_;
    /** Volume */
    Volume::Pointer vol_;
    /** Search radius */
    double radius_;
    /** Search direction */
    Direction direction_{Direction::Bidirectional};
    /** Search sampling interval */
    double interval_{1.0};
    /** Result */
    Texture result_;
    /** Calculate the size of each neighborhood based on current options */
    size_t neighborhood_count_();
};

}  // texturing
}  // volcart
