#!/usr/bin/env python3

import argparse
import difflib
from fnmatch import fnmatch
import logging
import os
import re
import sys
from distutils.version import LooseVersion

import common

# The version we care about
program_name = 'clang-format'


class ClangFormatter:
    # Blacklist certain files - tests, examples, etc. List entries should be in
    # the style of unix globs (e.g. *.cpp matches all files in the current dir
    # ending in .cpp) or full file paths.
    BLACKLIST = [
        # Not code that we control
        'external/*',
    ]

    def __init__(self, path_to_cf: str) -> None:
        self.path = path_to_cf
        self.toplevel = common.callo('git rev-parse --show-toplevel')

    def __str__(self):
        return self.path

    @property
    def version(self) -> LooseVersion:
        return LooseVersion(
            common.callo(' '.join([self.path, '--version'])).split()[2]
        )

    # Lint a given file - return whether or not the file is formatted correctly
    def lint(self, source_file: str, print_output: bool = False) -> bool:
        '''
        Lint `source_file` with clang-format, optionally showing the diff.
        '''
        if self.is_blacklisted(source_file):
            logging.debug(f'Skipping {source_file}, blacklisted')
            return True

        # Get original and formatted text
        with open(source_file, 'r', errors='ignore') as original_file:
            original_text = original_file.read()
        formatted_text = common.callo([self.path, '--style=file', source_file])

        # Create some nice git-like metadata for the diff
        relpath = os.path.relpath(source_file, self.toplevel)
        fromfile = os.path.join('a', relpath)
        tofile = os.path.join('b', relpath)

        diff = list(
            difflib.unified_diff(
                original_text.splitlines(),
                formatted_text.splitlines(),
                fromfile=fromfile,
                tofile=tofile
            )
        )

        if diff:
            print(f'Found formatting changes for file: {source_file}')

            if print_output:
                print(f'To fix, run "{self.path} --style=file -i {source_file}"')
                print('Suggested changes:')
                for line in diff:
                    print(line.strip())
                print()

        return not diff

    def is_blacklisted(self, source_file: str) -> bool:
        '''
        Checks whether `source_file` is blacklisted from tool checks.
        '''
        return any(fnmatch(source_file, pattern) for pattern in self.BLACKLIST)



def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser('clang-format')
    parser.add_argument(
        '-c',
        '--clang-format-path',
        help='path to clang-format',
        metavar='PATH',
        dest='path',
    )
    parser.add_argument(
        '--print-output',
        help='hide file diff generated by clang-format',
        default=False,
        action='store_true',
    )
    parser.add_argument(
        '-A',
        '--all-files',
        help='Operate on all files under revision control',
        default=False,
        action='store_true',
    )
    parser.add_argument(
        '-v',
        '--verbose',
        help='Increase logging',
        default=False,
        action='store_true',
    )
    return parser.parse_args()


def main() -> bool:
    args = parse_arguments()

    # Set up some logging
    level = logging.INFO if not args.verbose else logging.DEBUG
    logging.basicConfig(
        stream=sys.stdout,
        level=level,
        format='%(asctime)s %(name)s %(levelname)s %(message)s',
        datefmt='%m-%d %H:%M',
    )

    # Find clang-format, validate version
    path_to_cf = common.find_binary(program_name, args.path)
    cf = ClangFormatter(path_to_cf)
    if cf.version < common.MIN_VERSION_REQUIRED:
        logging.error(
            f'''Incorrect version of {program_name}: got {cf.version} but at \
                least {common.MIN_VERSION_REQUIRED} is required'''
        )
        sys.exit(1)

    # Find changed source files.
    source_files = re.compile(r'\.(h|hpp|c|cpp)$')
    if args.all_files:
        files = common.all_files()
    else:
        files = common.changed_files(compare_to='origin/develop')
    changes = [f for f in files if re.search(source_files, f)]

    # Validate each with clang-format
    lint_clean = []
    for change in changes:
        lint_clean.append(cf.lint(change, print_output=args.print_output))
    return all(lint_clean)


if __name__ == '__main__':
    sys.exit(int(not main()))
