FetchContent_Declare(
    smgl
    GIT_REPOSITORY https://gitlab.com/educelab/smgl.git
    GIT_TAG v0.10.1
    CMAKE_CACHE_ARGS
        -DSMGL_BUILD_JSON:BOOL=ON
        -DSMGL_USE_BOOSTFS:BOOL=ON
        -DSMGL_BUILD_TESTS:BOOL=OFF
        -DSMGL_BUILD_DOCS:BOOL=OFF
    EXCLUDE_FROM_ALL
)
set(SMGL_BUILD_JSON ${VC_BUILD_JSON} CACHE INTERNAL "")
set(SMGL_USE_BOOSTFS ${VC_USE_BOOSTFS} CACHE INTERNAL "")
set(SMGL_BUILD_TESTS OFF CACHE INTERNAL "")
set(SMGL_BUILD_DOCS OFF CACHE INTERNAL "")
FetchContent_MakeAvailable(smgl)
