# Simple workflow for deploying static content to GitHub Pages
name: Build and deploy docs to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Runs on pull requests to develop
  pull_request:
    branches:
      - "develop"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages-${{ github.ref_name }}"
  cancel-in-progress: false

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    container: ghcr.io/educelab/ci-docker:static.12.1
    timeout-minutes: 180
    env:
      CMAKE_PREFIX_PATH: "/usr/local/Qt-6.7.2/"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install documentation requirements
        run: |
          apt-get -y update
          apt-get install --fix-missing --fix-broken -y doxygen graphviz

      - name: Build documentation
        run: |
          cmake -S . -B build/ -GNinja -DVC_BUILD_DOCS=ON -DVC_BUILD_APPS=OFF -DVC_BUILD_UTILS=OFF
          cmake --build build/ --target docs
          mv build/docs/html/ public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
          
  deploy:
    name: Deploy documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref_name == 'develop' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
